apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-reader-binding
  namespace: kube-system
subjects:
  - kind: User
    name: your-user-name
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: node-reader
  apiGroup: rbac.authorization.k8s.io
