apiVersion: v1
kind: Service
metadata:
  name: dental-office-online-scheduling-system
spec:
  selector:
    app: dental-office-online-scheduling-system
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3000
  type: LoadBalancer
